# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generat.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GenerationPass(object):
    def setupUi(self, GenerationPass):
        GenerationPass.setObjectName("GenerationPass")
        GenerationPass.resize(333, 302)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/key_black_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GenerationPass.setWindowIcon(icon)
        GenerationPass.setStyleSheet("QWidget {\n"
"    background-color: #b0b7c6;\n"
"    color: black;\n"
"    font-family: \'Gill Sans\', \'Gill Sans MT\', Calibri, \'Trebuchet MS\', sans-serif;\n"
"    font-size: 16pt;\n"
"    margin: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    border: 2px solid #a2a2d0;\n"
"    background-color: #baacc7;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QPushButton#LowerButton,\n"
"#DigitButton, \n"
"#SpecialButton, \n"
"#UpperButton{\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #b7a3cc;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 4px solid #8360a8;\n"
"    border-radius: 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: #9d82ba;\n"
"    border-color: #8360a8;\n"
"\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(GenerationPass)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalFrame = QtWidgets.QFrame(GenerationPass)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame.sizePolicy().hasHeightForWidth())
        self.horizontalFrame.setSizePolicy(sizePolicy)
        self.horizontalFrame.setStyleSheet("QFrame{\n"
"    border: 2px solid #a2a2d0;\n"
"    border-radius: 5px;\n"
"    margin-right: 0;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    border-color: #9d82ba;\n"
"}")
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalFrame)
        self.lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border: 2px solid #b7a3cc;\n"
"    background-color: #d5d5f0;\n"
"    margin: 0;\n"
"    font-size: 20pt;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.RestarButton = QtWidgets.QPushButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RestarButton.sizePolicy().hasHeightForWidth())
        self.RestarButton.setSizePolicy(sizePolicy)
        self.RestarButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RestarButton.setStyleSheet("QPushButton{\n"
"    margin-right: 0;\n"
"    margin-left: 0;\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 2px solid #8360a8;\n"
"    border-radius: 3px;\n"
"\n"
"}")
        self.RestarButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/replay_black_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.RestarButton.setIcon(icon1)
        self.RestarButton.setIconSize(QtCore.QSize(22, 26))
        self.RestarButton.setObjectName("RestarButton")
        self.horizontalLayout.addWidget(self.RestarButton)
        self.CopyButton = QtWidgets.QPushButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CopyButton.sizePolicy().hasHeightForWidth())
        self.CopyButton.setSizePolicy(sizePolicy)
        self.CopyButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CopyButton.setStyleSheet("QPushButton{\n"
"    margin-right: 0;\n"
"    margin-left: 0;\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 2px solid #8360a8;\n"
"    border-radius: 3px;\n"
"\n"
"}")
        self.CopyButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/content_copy_black_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CopyButton.setIcon(icon2)
        self.CopyButton.setIconSize(QtCore.QSize(22, 26))
        self.CopyButton.setObjectName("CopyButton")
        self.horizontalLayout.addWidget(self.CopyButton)
        self.verticalLayout.addWidget(self.horizontalFrame)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LabelStronk = QtWidgets.QLabel(GenerationPass)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelStronk.sizePolicy().hasHeightForWidth())
        self.LabelStronk.setSizePolicy(sizePolicy)
        self.LabelStronk.setText("")
        self.LabelStronk.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelStronk.setObjectName("LabelStronk")
        self.horizontalLayout_2.addWidget(self.LabelStronk)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.SliderLenght = QtWidgets.QSlider(GenerationPass)
        self.SliderLenght.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SliderLenght.setStyleSheet("QSlider::groove:horizontal{\n"
"    background-color: transparent;\n"
"    height: 5 px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal{\n"
"    background-color: #9d82ba;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal{\n"
"    background-color: #b7a3cc;\n"
"}\n"
"\n"
"QSlider::handle:horizontal{\n"
"    background-color: white;\n"
"    width: 22px;\n"
"    border-radius: 10px;\n"
"    margin-top: -8px;\n"
"    margin-bottom: -8px;\n"
"}")
        self.SliderLenght.setOrientation(QtCore.Qt.Horizontal)
        self.SliderLenght.setObjectName("SliderLenght")
        self.horizontalLayout_3.addWidget(self.SliderLenght)
        self.SpinboxLenght = QtWidgets.QSpinBox(GenerationPass)
        self.SpinboxLenght.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SpinboxLenght.setStyleSheet("QSpinBox{\n"
"    border: 2px solid #8360a8;\n"
"    border-radius: 4px;\n"
"    background: transparent;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QSpinBox:hover{\n"
"    border-color: #9d82ba;\n"
"}\n"
"")
        self.SpinboxLenght.setAlignment(QtCore.Qt.AlignCenter)
        self.SpinboxLenght.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.SpinboxLenght.setMaximum(100)
        self.SpinboxLenght.setProperty("value", 8)
        self.SpinboxLenght.setObjectName("SpinboxLenght")
        self.horizontalLayout_3.addWidget(self.SpinboxLenght)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.LowerButton = QtWidgets.QPushButton(GenerationPass)
        self.LowerButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LowerButton.setCheckable(True)
        self.LowerButton.setChecked(True)
        self.LowerButton.setObjectName("LowerButton")
        self.horizontalLayout_4.addWidget(self.LowerButton)
        self.UpperButton = QtWidgets.QPushButton(GenerationPass)
        self.UpperButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.UpperButton.setCheckable(True)
        self.UpperButton.setChecked(True)
        self.UpperButton.setObjectName("UpperButton")
        self.horizontalLayout_4.addWidget(self.UpperButton)
        self.DigitButton = QtWidgets.QPushButton(GenerationPass)
        self.DigitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DigitButton.setCheckable(True)
        self.DigitButton.setChecked(True)
        self.DigitButton.setObjectName("DigitButton")
        self.horizontalLayout_4.addWidget(self.DigitButton)
        self.SpecialButton = QtWidgets.QPushButton(GenerationPass)
        self.SpecialButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SpecialButton.setCheckable(True)
        self.SpecialButton.setChecked(False)
        self.SpecialButton.setObjectName("SpecialButton")
        self.horizontalLayout_4.addWidget(self.SpecialButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(GenerationPass)
        QtCore.QMetaObject.connectSlotsByName(GenerationPass)

    def retranslateUi(self, GenerationPass):
        _translate = QtCore.QCoreApplication.translate
        GenerationPass.setWindowTitle(_translate("GenerationPass", "Generation"))
        self.RestarButton.setShortcut(_translate("GenerationPass", "Ctrl+R"))
        self.CopyButton.setShortcut(_translate("GenerationPass", "Ctrl+C"))
        self.LowerButton.setText(_translate("GenerationPass", "a-z"))
        self.UpperButton.setText(_translate("GenerationPass", "A-Z"))
        self.DigitButton.setText(_translate("GenerationPass", "0-9"))
        self.SpecialButton.setText(_translate("GenerationPass", "#$?"))
import resours
