# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(788, 638)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/key_black_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #b0b7c6;\n"
"    color: black;\n"
"    font-family: \'Gill Sans\', \'Gill Sans MT\', Calibri, \'Trebuchet MS\', sans-serif;\n"
"     font-size: 16pt;\n"
"    margin: 3px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    border: 2px solid #a2a2d0;\n"
"    background-color: #baacc7;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton#LowerButton,\n"
"#DigitButton, \n"
"#SpecialButton, \n"
"#UpperButton{\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #b7a3cc;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 4px solid #8360a8;\n"
"    border-radius: 8px;\n"
"\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: #9d82ba;\n"
"    border-color: #8360a8;\n"
"\n"
"}\n"
"QLineEdit{\n"
"    border: 2px solid #b7a3cc;\n"
"    background-color: #d5d5f0;\n"
"    margin: 0;\n"
"    font-size: 17pt;\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.status_lab = QtWidgets.QLabel(self.centralwidget)
        self.status_lab.setGeometry(QtCore.QRect(10, 590, 771, 51))
        self.status_lab.setText("")
        self.status_lab.setObjectName("status_lab")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(20, 10, 761, 581))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.MainLoginButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainLoginButton.sizePolicy().hasHeightForWidth())
        self.MainLoginButton.setSizePolicy(sizePolicy)
        self.MainLoginButton.setMinimumSize(QtCore.QSize(0, 69))
        font = QtGui.QFont()
        font.setFamily("Gill Sans")
        font.setPointSize(16)
        font.setItalic(False)
        self.MainLoginButton.setFont(font)
        self.MainLoginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MainLoginButton.setIconSize(QtCore.QSize(330, 70))
        self.MainLoginButton.setObjectName("MainLoginButton")
        self.verticalLayout_2.addWidget(self.MainLoginButton)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Gill Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.ServerEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ServerEdit.sizePolicy().hasHeightForWidth())
        self.ServerEdit.setSizePolicy(sizePolicy)
        self.ServerEdit.setObjectName("ServerEdit")
        self.verticalLayout_2.addWidget(self.ServerEdit)
        self.LoginEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoginEdit.sizePolicy().hasHeightForWidth())
        self.LoginEdit.setSizePolicy(sizePolicy)
        self.LoginEdit.setObjectName("LoginEdit")
        self.verticalLayout_2.addWidget(self.LoginEdit)
        self.PasswEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PasswEdit.sizePolicy().hasHeightForWidth())
        self.PasswEdit.setSizePolicy(sizePolicy)
        self.PasswEdit.setObjectName("PasswEdit")
        self.verticalLayout_2.addWidget(self.PasswEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.AppendButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AppendButton.sizePolicy().hasHeightForWidth())
        self.AppendButton.setSizePolicy(sizePolicy)
        self.AppendButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/save_black_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AppendButton.setIcon(icon1)
        self.AppendButton.setIconSize(QtCore.QSize(40, 58))
        self.AppendButton.setObjectName("AppendButton")
        self.horizontalLayout_2.addWidget(self.AppendButton)
        self.CopyButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CopyButton.sizePolicy().hasHeightForWidth())
        self.CopyButton.setSizePolicy(sizePolicy)
        self.CopyButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/content_copy_black_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CopyButton.setIcon(icon2)
        self.CopyButton.setIconSize(QtCore.QSize(40, 58))
        self.CopyButton.setObjectName("CopyButton")
        self.horizontalLayout_2.addWidget(self.CopyButton)
        self.DeleteButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DeleteButton.sizePolicy().hasHeightForWidth())
        self.DeleteButton.setSizePolicy(sizePolicy)
        self.DeleteButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/delete_black_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DeleteButton.setIcon(icon3)
        self.DeleteButton.setIconSize(QtCore.QSize(53, 58))
        self.DeleteButton.setObjectName("DeleteButton")
        self.horizontalLayout_2.addWidget(self.DeleteButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.PasswGener = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(180)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PasswGener.sizePolicy().hasHeightForWidth())
        self.PasswGener.setSizePolicy(sizePolicy)
        self.PasswGener.setMinimumSize(QtCore.QSize(180, 0))
        self.PasswGener.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PasswGener.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PasswGener.setObjectName("PasswGener")
        self.verticalLayout_2.addWidget(self.PasswGener)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SearchLine = QtWidgets.QLineEdit(self.layoutWidget1)
        self.SearchLine.setObjectName("SearchLine")
        self.horizontalLayout.addWidget(self.SearchLine)
        self.ResumeButton = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResumeButton.sizePolicy().hasHeightForWidth())
        self.ResumeButton.setSizePolicy(sizePolicy)
        self.ResumeButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/replay_black_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ResumeButton.setIcon(icon4)
        self.ResumeButton.setIconSize(QtCore.QSize(37, 40))
        self.ResumeButton.setObjectName("ResumeButton")
        self.horizontalLayout.addWidget(self.ResumeButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setStyleSheet("background-color: rgb(230, 240, 255);\n"
"color: black;\n"
"font-family: \'Gill Sans\', \'Gill Sans MT\', Calibri, \'Trebuchet MS\', sans-serif;\n"
"font-size: 9pt;\n"
"margin: 0px;\n"
"\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.TableButton = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TableButton.sizePolicy().hasHeightForWidth())
        self.TableButton.setSizePolicy(sizePolicy)
        self.TableButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TableButton.setObjectName("TableButton")
        self.verticalLayout.addWidget(self.TableButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PasswordManager"))
        self.MainLoginButton.setText(_translate("MainWindow", "Log in or register"))
        self.label.setText(_translate("MainWindow", "Adding data"))
        self.ServerEdit.setPlaceholderText(_translate("MainWindow", "Service"))
        self.LoginEdit.setPlaceholderText(_translate("MainWindow", "Login"))
        self.PasswEdit.setPlaceholderText(_translate("MainWindow", "Password"))
        self.PasswGener.setText(_translate("MainWindow", "Password generation"))
        self.SearchLine.setPlaceholderText(_translate("MainWindow", "Promt"))
        self.TableButton.setText(_translate("MainWindow", "Save table"))
import resours
