# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterWidget(object):
    def setupUi(self, RegisterWidget):
        RegisterWidget.setObjectName("RegisterWidget")
        RegisterWidget.resize(290, 345)
        RegisterWidget.setMinimumSize(QtCore.QSize(290, 0))
        icon = QtGui.QIcon()

        icon.addPixmap(QtGui.QPixmap(":/newPrefix/key_black_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RegisterWidget.setWindowIcon(icon)
        RegisterWidget.setStyleSheet("QWidget {\n"
"    background-color: #b0b7c6;\n"
"    color: black;\n"
"    font-family: \'Gill Sans\', \'Gill Sans MT\', Calibri, \'Trebuchet MS\', sans-serif;\n"
"    font-size: 13pt;\n"
"    margin: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    border: 2px solid #a2a2d0;\n"
"    background-color: #baacc7;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #b7a3cc;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 4px solid #8360a8;\n"
"    border-radius: 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: #9d82ba;\n"
"    border-color: #8360a8;\n"
"\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: 2px solid #b7a3cc;\n"
"    background-color: #d5d5f0;\n"
"    margin: 0;\n"
"    font-size: 14pt;\n"
"    border-radius: 8px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(RegisterWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(RegisterWidget)
        font = QtGui.QFont()
        font.setFamily("Gill Sans")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.LoginEdit = QtWidgets.QLineEdit(RegisterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoginEdit.sizePolicy().hasHeightForWidth())
        self.LoginEdit.setSizePolicy(sizePolicy)
        self.LoginEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.LoginEdit.setInputMask("")
        self.LoginEdit.setText("")
        self.LoginEdit.setObjectName("LoginEdit")
        self.verticalLayout.addWidget(self.LoginEdit)
        self.PasswEdit = QtWidgets.QLineEdit(RegisterWidget)
        self.PasswEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PasswEdit.sizePolicy().hasHeightForWidth())
        self.PasswEdit.setSizePolicy(sizePolicy)
        self.PasswEdit.setInputMask("")
        self.PasswEdit.setText("")
        self.PasswEdit.setObjectName("PasswEdit")
        self.verticalLayout.addWidget(self.PasswEdit)
        self.InButton = QtWidgets.QPushButton(RegisterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InButton.sizePolicy().hasHeightForWidth())
        self.InButton.setSizePolicy(sizePolicy)
        self.InButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.InButton.setIconSize(QtCore.QSize(16, 16))
        self.InButton.setObjectName("InButton")
        self.verticalLayout.addWidget(self.InButton)
        self.UpButton = QtWidgets.QPushButton(RegisterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UpButton.sizePolicy().hasHeightForWidth())
        self.UpButton.setSizePolicy(sizePolicy)
        self.UpButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.UpButton.setObjectName("UpButton")
        self.verticalLayout.addWidget(self.UpButton)
        self.statuslabel = QtWidgets.QLabel(RegisterWidget)
        self.statuslabel.setText("")
        self.statuslabel.setObjectName("statuslabel")
        self.verticalLayout.addWidget(self.statuslabel)

        self.retranslateUi(RegisterWidget)
        QtCore.QMetaObject.connectSlotsByName(RegisterWidget)

    def retranslateUi(self, RegisterWidget):
        _translate = QtCore.QCoreApplication.translate
        RegisterWidget.setWindowTitle(_translate("RegisterWidget", "Form"))
        self.label.setText(_translate("RegisterWidget", "Authorization"))
        self.LoginEdit.setPlaceholderText(_translate("RegisterWidget", "Input Login"))
        self.PasswEdit.setPlaceholderText(_translate("RegisterWidget", "Input Password"))
        self.InButton.setText(_translate("RegisterWidget", "Sign In"))
        self.UpButton.setText(_translate("RegisterWidget", "Sign Up"))

import resours
